################################ Prod DataBase Properties ###########################################
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Production CORS configuration (STRICTLY NO LOCALHOST)
cors.allowed-origins=https://sensei.org.in,https://www.sensei.org.in,https://sensei-website-preview.vercel.app
