package com.sensei.backend.enums;

public enum LifeSkillType {
    EMPATHY,
    EFFECTIVE_COMMUNICATION,
    PROBLEM_SOLVING,
    CRITICAL_THINKING,
    DECISION_MAKING,
    SELF_AWARENESS,
    COPING_WITH_STRESS,
    COPING_WITH_EMOTIONS,
    CREATIVE_THINKING,
    INTERPERSONAL_RELATIONSHIP
}
