-- dummy_data.sql
-- Run this script on your local MySQL database to populate it with dummy data for testing.
-- Note: You MUST run the Spring Boot application at least once before running this script 
-- so that the tables are automatically generated by the schema.sql!

-- ==========================================
-- 1. PRICING PLANS & SUBJECTS
-- ==========================================
INSERT IGNORE INTO pricing_plan (id, name, price, duration_in_months, status, created_at, updated_at) 
VALUES ('11111111-1111-1111-1111-111111111111', 'Starter Plan', 9900, 1, 'ACTIVE', NOW(), NOW());

INSERT IGNORE INTO pricing_plan (id, name, price, duration_in_months, status, created_at, updated_at) 
VALUES ('22222222-2222-2222-2222-222222222222', 'Pro Plan', 19900, 12, 'ACTIVE', NOW(), NOW());

INSERT IGNORE INTO subject (id, name, description, is_active, created_at, updated_at)
VALUES ('33333333-3333-3333-3333-333333333333', 'Mathematics', 'Basic Math Skills', 1, NOW(), NOW());

INSERT IGNORE INTO module (id, subject_id, name, order_index, is_active, created_at, updated_at)
VALUES ('44444444-4444-4444-4444-444444444444', '33333333-3333-3333-3333-333333333333', 'Algebra', 1, 1, NOW(), NOW());

INSERT IGNORE INTO sub_module (id, module_id, name, order_index, is_active, created_at, updated_at)
VALUES ('55555555-5555-5555-5555-555555555555', '44444444-4444-4444-4444-444444444444', 'Linear Equations', 1, 1, NOW(), NOW());

INSERT IGNORE INTO pricing_plan_subject (id, pricing_plan_id, subject_id, created_at, updated_at)
VALUES ('66666666-6666-6666-6666-666666666666', '11111111-1111-1111-1111-111111111111', '33333333-3333-3333-3333-333333333333', NOW(), NOW());

INSERT IGNORE INTO pricing_plan_subject (id, pricing_plan_id, subject_id, created_at, updated_at)
VALUES ('77777777-7777-7777-7777-777777777777', '22222222-2222-2222-2222-222222222222', '33333333-3333-3333-3333-333333333333', NOW(), NOW());


-- ==========================================
-- 2. PARENT & CHILD USERS
-- ==========================================
-- Dummy Parent
INSERT IGNORE INTO parent_user (parent_id, email, name, phone, created_at, updated_at)
VALUES ('88888888-8888-8888-8888-888888888888', 'testparent@sensei.org', 'Test Parent', '9876543210', NOW(), NOW());

-- Dummy Child (Active Pro Plan)
INSERT IGNORE INTO child_user (child_id, parent_id, child_name, gender, grade, age_group, active_plan_id, plan_start_date, plan_expiry_date, plan_status, created_at, updated_at)
VALUES ('99999999-9999-9999-9999-999999999999', '88888888-8888-8888-8888-888888888888', 'Test Child', 'Female', '5th Grade', '10-12', '22222222-2222-2222-2222-222222222222', DATE(NOW()), DATE_ADD(DATE(NOW()), INTERVAL 1 YEAR), 'ACTIVE', NOW(), NOW());


-- ==========================================
-- 3. DIGITAL ACTIVITIES & QUESTIONS
-- ==========================================
-- Digital Activity
INSERT IGNORE INTO digital_activity (id, sub_module_id, title, difficulty, game_type, instructions, is_active, order_index, created_at, updated_at)
VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '55555555-5555-5555-5555-555555555555', 'Solve for X', 'EASY', 'QUIZ', 'Find the value of X in the given equations.', 1, 1, NOW(), NOW());

-- Question 1
INSERT IGNORE INTO question (id, digital_activity_id, question_text, explanation, hint, is_active, order_index)
VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'If X + 5 = 10, what is X?', 'Subtract 5 from both sides to get X = 5', 'What number plus 5 equals 10?', 1, 1);

-- Options for Q1
INSERT IGNORE INTO question_option (id, question_id, option_text, is_correct, is_active, order_index)
VALUES ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '5', 1, 1, 1);
INSERT IGNORE INTO question_option (id, question_id, option_text, is_correct, is_active, order_index)
VALUES ('dddddddd-dddd-dddd-dddd-dddddddddddd', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '10', 0, 1, 2);
INSERT IGNORE INTO question_option (id, question_id, option_text, is_correct, is_active, order_index)
VALUES ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '15', 0, 1, 3);


-- ==========================================
-- 4. PARENT ONBOARDING QUIZ (REAL)
-- ==========================================
-- Parent Quiz Q1
INSERT IGNORE INTO parent_quiz_question (id, question_text, is_active, order_index, created_at)
VALUES ('f1111111-f111-f111-f111-f11111111111', 'How does your child typically react to a completely new and difficult challenge?', 1, 1, NOW());

-- Options for Q1
INSERT IGNORE INTO parent_quiz_option (id, question_id, option_text, created_at)
VALUES ('f2222222-f222-f222-f222-f22222222222', 'f1111111-f111-f111-f111-f11111111111', 'Jumps right in and tries immediately', NOW());
INSERT IGNORE INTO parent_quiz_option (id, question_id, option_text, created_at)
VALUES ('f3333333-f333-f333-f333-f33333333333', 'f1111111-f111-f111-f111-f11111111111', 'Asks questions to understand before trying', NOW());
INSERT IGNORE INTO parent_quiz_option (id, question_id, option_text, created_at)
VALUES ('f4444444-f444-f444-f444-f44444444444', 'f1111111-f111-f111-f111-f11111111111', 'Avoids the challenge or gives up easily', NOW());

-- Map Life Skills to Options
INSERT IGNORE INTO parent_quiz_option_life_skills (option_id, life_skill) VALUES ('f2222222-f222-f222-f222-f22222222222', 'CONFIDENCE');
INSERT IGNORE INTO parent_quiz_option_life_skills (option_id, life_skill) VALUES ('f3333333-f333-f333-f333-f33333333333', 'COMMUNICATION');

-- Parent Quiz Q2
INSERT IGNORE INTO parent_quiz_question (id, question_text, is_active, order_index, created_at)
VALUES ('f5555555-f555-f555-f555-f55555555555', 'When playing in a group, your child usually...', 1, 2, NOW());

-- Options for Q2
INSERT IGNORE INTO parent_quiz_option (id, question_id, option_text, created_at)
VALUES ('f6666666-f666-f666-f666-f66666666666', 'f5555555-f555-f555-f555-f55555555555', 'Takes charge and directs the group', NOW());
INSERT IGNORE INTO parent_quiz_option (id, question_id, option_text, created_at)
VALUES ('f7777777-f777-f777-f777-777777777777', 'f5555555-f555-f555-f555-f55555555555', 'Listens carefully to others'' ideas', NOW());

-- Map Life Skills to Options
INSERT IGNORE INTO parent_quiz_option_life_skills (option_id, life_skill) VALUES ('f6666666-f666-f666-f666-f66666666666', 'LEADERSHIP');
INSERT IGNORE INTO parent_quiz_option_life_skills (option_id, life_skill) VALUES ('f7777777-f777-f777-f777-777777777777', 'EMPATHY');
